# Generated by Django 4.1.2 on 2022-11-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0012_alter_comentario_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comentario',
        ),
    ]
