# Generated by Django 4.1.2 on 2022-11-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0013_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('creador', models.CharField(max_length=30)),
                ('encabezado', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=5000)),
                ('fechaCreacion', models.DateTimeField()),
            ],
        ),
    ]
